FROM jenkins/jenkins:lts

USER root

# Python, pip, 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && pip install --no-cache-dir requests jira xmltodict

# Jenkins 실행 유저로 다시 전환
USER jenkins
